name:                hallizkeer
version:             0.1.0.0
github:              "YairiLab/hallizkeer"
license:             MIT
author:              "Phil Owen"
maintainer:          "hiroki@yairilab.net"
copyright:           "2018 Phil Owen"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/YairiLab/hallizkeer>

dependencies:
- base >= 4.7 && < 5
- transformers

library:
  source-dirs: src

executables:
  hallizkeer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hallizkeer
